In [27]:
import numpy as np

In [28]:
#1
a = np.arange(10)
a[1:10] = 0
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [29]:
#2
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [30]:
#3
def reverse(x):
    return x[::-1]
reverse(b)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [49]:
#4
def find_nonzero(x):
    return np.nonzero(x)
x = np.array([1,2,0,0,4,0])
find_nonzero(x)
x[find_nonzero(x)]

array([1, 2, 4])

In [32]:
#5
c = np.random.normal(0,1,(3,3,3))
c

array([[[ -1.19354272e-03,  -1.07230597e+00,   3.44835375e-01],
        [  3.00290166e-01,   7.87190060e-01,  -7.58726962e-01],
        [  4.98388844e-01,   1.06168226e-01,   9.96658445e-01]],

       [[ -1.05710099e+00,   1.20140006e+00,  -1.02807846e-02],
        [  4.19231458e-01,   7.87529606e-01,  -2.20271310e-01],
        [ -6.59741192e-01,   8.96218047e-01,  -4.79953245e-01]],

       [[ -3.50074208e-01,   2.40581054e+00,   2.24797595e-02],
        [ -6.80268268e-01,  -4.89261814e-01,  -1.44363863e+00],
        [ -3.15740831e+00,   4.68878742e-01,   6.50840673e-01]]])

In [33]:
#6
d = np.random.rand(10,10)
print(d)
dmax = np.max(d[:,3])
dmin = np.min(d[1,:])
print(dmax,dmin)


[[  1.96158301e-01   9.54988639e-01   1.13057344e-01   8.84906346e-01
    3.60352351e-01   3.72292160e-01   3.46287958e-02   2.22954869e-01
    8.10249086e-02   5.58021589e-01]
 [  9.89759560e-01   7.35475762e-01   2.77827353e-01   9.52476741e-02
    4.94582274e-01   4.42572904e-01   4.03873774e-01   6.56352414e-01
    3.32183823e-01   2.82362948e-01]
 [  7.68895790e-04   3.75490235e-01   6.58707288e-02   8.74208071e-01
    7.25930274e-01   4.34337269e-01   8.32067174e-01   2.17467944e-01
    4.58765419e-01   3.72447572e-01]
 [  1.31501080e-01   1.13600738e-01   5.01914354e-01   8.99351455e-01
    2.65074810e-01   7.13936785e-02   9.09988970e-01   4.51628549e-01
    1.26493356e-01   7.65955893e-01]
 [  9.63950208e-01   7.75809839e-01   4.60838044e-01   1.54160972e-01
    5.44381434e-01   9.95226285e-01   5.26580271e-01   1.70699389e-01
    7.04501070e-01   9.34464253e-01]
 [  5.71458275e-01   9.46240459e-01   2.19340592e-01   6.10497617e-02
    5.10560972e-01   7.37490416e-01   5.71611

In [34]:
#7
e = np.linspace(0, 1, 12, endpoint = True)[1:-1]
e

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

In [35]:
#8
f = np.random.rand(10)
f.sort()
f

array([ 0.05767896,  0.08028872,  0.09434191,  0.31102898,  0.32563959,
        0.34524389,  0.35383083,  0.43936804,  0.50791723,  0.95580785])

In [38]:
#9
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])
C = np.array([2, 4, 6, 8, 10])
D = np.array([2, 4, 6, 8, 10])

def is_equal(A, B):
    return A == B

print(is_equal(A, B))
print(is_equal(C, D))

[False False False False False]
[ True  True  True  True  True]


In [16]:
#10
g = d - d.mean(axis = 1, keepdims = True)
print(g)

[[-0.15829762 -0.32788507  0.11064887 -0.00136602  0.30664405 -0.09355279
  -0.05694624  0.33946673 -0.00849854 -0.11021338]
 [-0.005883    0.27938999  0.24395353  0.36224465 -0.32168364 -0.28644282
  -0.49198099  0.0409939   0.43349318 -0.25408481]
 [-0.34362387 -0.05096498  0.02711879  0.3619433   0.04552173 -0.48228966
  -0.03084059  0.30144036  0.06718954  0.10450536]
 [ 0.25949129 -0.34141021  0.34578127 -0.4202225   0.23221073 -0.04317365
  -0.50194851 -0.09213083  0.30871318  0.25268924]
 [ 0.1428653   0.22120043 -0.01712093  0.17074358  0.36865984 -0.32263103
   0.02601095 -0.06979246 -0.19708176 -0.32285393]
 [ 0.3002868   0.36912653 -0.50481578 -0.50617281 -0.13731052 -0.45042583
   0.26449868  0.39876619  0.20456038  0.06148636]
 [-0.25347894  0.22062533  0.43638211 -0.12548206 -0.25793395  0.06990651
  -0.25856393 -0.13130425 -0.22109951  0.52094869]
 [-0.27971957  0.22847013 -0.58858146  0.19343425  0.21095198 -0.10081498
   0.18852946 -0.0558102   0.0688639   0.1346765 ]


In [46]:
#11
h = np.random.rand(5, 5, 3)
i = np.random.rand(5, 5)
j = (h * i[:, :, None])
print("Multiply an array of dimension (5,5,3) with an array with dimensions (5,5):", j)

k = np.random.rand(3, 5, 5)
l = np.random.rand(5, 5)
m = (h * i[:, :, None])
print("Then multiply an array of dimension (3,5,5) with an array of dimension (5,5):", m)

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5): [[[ 0.04908585  0.37898366  0.23140798]
  [ 0.15256445  0.28329988  0.12171972]
  [ 0.13925066  0.75713298  0.31855991]
  [ 0.02980105  0.18917019  0.2750598 ]
  [ 0.0936675   0.09651169  0.0404321 ]]

 [[ 0.25702555  0.11613239  0.38337727]
  [ 0.67184945  0.31872014  0.43801649]
  [ 0.35212247  0.29727052  0.229682  ]
  [ 0.11634371  0.17180634  0.43188336]
  [ 0.26557119  0.11389297  0.01691338]]

 [[ 0.30930579  0.44541496  0.06891259]
  [ 0.15038251  0.17718746  0.70398568]
  [ 0.11878353  0.19419827  0.01762193]
  [ 0.24744365  0.57656252  0.08855676]
  [ 0.02985827  0.04536005  0.04501688]]

 [[ 0.05936985  0.01385829  0.04916371]
  [ 0.32004696  0.15449755  0.55952569]
  [ 0.63084282  0.20967918  0.2811788 ]
  [ 0.16226059  0.43990172  0.37749316]
  [ 0.41228574  0.78920401  0.00935785]]

 [[ 0.02804436  0.02750478  0.07884822]
  [ 0.00773537  0.00931079  0.0261254 ]
  [ 0.42526873  0.40726366  0.203261

In [77]:
#12
Z = np.arange(1, 15)
q = []
for n in Z:
    if n < 12:
        p = np.array([n, n + 1, n + 2, n + 3])
        q.append([p])
        R = np.asarray(q)
    elif n == 12 or n == 13:  
        continue
    else:
        print(R)

[[[ 1  2  3  4]]

 [[ 2  3  4  5]]

 [[ 3  4  5  6]]

 [[ 4  5  6  7]]

 [[ 5  6  7  8]]

 [[ 6  7  8  9]]

 [[ 7  8  9 10]]

 [[ 8  9 10 11]]

 [[ 9 10 11 12]]

 [[10 11 12 13]]

 [[11 12 13 14]]]


In [84]:
#13
def cart2polar(xy): 
    x = xy[:,0] 
    y = xy[:,1]
    s = np.sqrt(x**2 + y**2)
    t = np.arctan2(y,x)
    return np.transpose(np.array([s,t]))

u = np.array([[7,3],[4,9]])
u

array([[7, 3],
       [4, 9]])

In [88]:
#14
import time
a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
time1
sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.
time2

time.time()
t = 

SyntaxError: invalid syntax (<ipython-input-88-e544ad433bd9>, line 10)

In [85]:
#15
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa

    return a*b
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [87]:
#16
data = np.loadtxt('../python4geosciences/data/burl1h2010.txt')

vdir = data[:,5]
vspd = data[:,6]

def wind(vdir, vspd):
    d = np.radians(vdir)
    u = (vspd)*np.cos(d)
    v = (vspd)*np.sin(d)
    return (u,v)